config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get 'main/index'
  get '/random' => 'main#random'
  get '/choose' => 'main#choose'
  get '/cluster_random' => 'main#random_cluster'
  get '/cluster' => 'main#cluster'

end

app/models/flag.rb
class Flag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
require 'flags/flagnode'

class MainController < ApplicationController

  def index
  end

  def choose
    @countries = Flag::all
  end

  def random
  end

  def random_cluster
    centroids = Flag::all.sample(params[:number].to_i).map.with_object({}) do |f, h|
      h[f.name.to_sym] = "on"
    end
    redirect_to action: :cluster, **centroids
  end

  def cluster
    centroids = Flag::where(name: params.keys).map do |centroid|
      FlagNode::new centroid
    end
    flags = Flag::all.map do |flag|
      FlagNode::new flag
    end
    algorithm = Carmenere::KMeans::Algorithm::new(centroids, flags) do |cluster|
      FlagNode::mean(cluster)
    end
    @clusters = algorithm.run.values
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/main_helper.rb
module MainHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Flagster | <%= params[:controller].capitalize %>
  </title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrap">
    <h1>
      <%= link_to 'Flagster', {action: 'index'} %>
    </h1>
    <%= yield %>
</div>
<footer>
  
</footer>
</body>
</html>

app/views/main/choose.html.erb
<h2>Choose!</h2>

<%= form_tag cluster_path, method: "get" do %>
    <div class="container-fluid countries">
        <% closed = false %>
        <% @countries.each.with_index do |c, i| %>
            <% if i % 6 == 0 %>
                <% closed = false %>
                <div class="row">
            <% end -%>
            <div class="col-xs-6 col-md-4">
                <%= check_box_tag c.name %>
                <%= label_tag c.name %>
                <%= image_tag("#{c.iso}.gif") if c.iso %>
            </div>
            <% if i % 6 == 5 %>
                <% closed = true %>
                </div> <!-- close row -->
            <% end -%>
        <% end -%>
        <% if not closed %>
            </div> <!-- close row -->
        <% end -%>


        <div class="row">
            <div class="col-md-4">
              <%= submit_tag 'Cluster!' %>
            </div>
        </div>
    </div>
<% end %>

app/views/main/cluster.html.erb
<h2>Clustered</h2>

<% @clusters.each.with_index do |cluster, i| %>
    <div class="container-fluid clustered-countries">
        <% closed = true %>
        <% cluster.each.with_index do |flag, j| %>
            <% if j % 6 == 0 %>
                <% closed = false %>
                <div class="row">
            <% end -%>
            <div class="col-xs-6 col-md-4">
                <%= image_tag("#{flag.iso}.gif") if flag.iso %>
                <%= flag %>
            </div>
            <% if j % 6 == 5 %>
                <% closed = true %>
                </div>
            <% end -%>
        <% end -%>
        <% if not closed %>
            </div>
        <% end -%>
    </div>
<% end -%>

app/views/main/index.html.erb
<h2>
    Get started
</h2>
<p>
    How will you get the algorithm started?
</p>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <%= link_to 'Choose initial centroids!', action: 'choose' %>
        </div>
        <div class="col-md-6">
            <%= link_to 'Random centroids!', action: 'random' %>
        </div>
    </div>
</div>

<h2>
    About
</h2>
<p>
    Flagster employs a <a href="http://en.wikipedia.org/wiki/K-means_clustering">K-means clustering algorithm</a> to classify flags according to their characteristics such as number of stripes, number of bars, main color, etc. The dataset employed can be found <a href="http://archive.ics.uci.edu/ml/datasets/Flags">here</a> and was developed by was  "collected primarily from the 'Collins Gem Guide to Flags'" (Collins Publishers, 1986).
</p>
<p>
    Donor:<br>
    Richard S. Forsyth<br>
    8 Grosvenor Avenue<br>
    Mapperley Park<br>
    Nottingham NG3 5DX<br>
    0602-621676<br>
    Date: 5/15/1990<br>
</p>
<p>
    Unfortunately, the dataset is a couple of decades old at the time of its development so that the flag icons that accompany them are not all accurate.
</p>
<p>
    Flagster was developed by <a href="https://github.com/jleeothon">Johnny Lee Othon</a>.
</p>
<p>
    Icons for flags can be found <a href="http://www.famfamfam.com/lab/icons/flags/">here</a>.
</p>

app/views/main/random.html.erb
<h2>Random!</h2>

<%= form_tag cluster_random_path, method: "get" do %>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <%= number_field_tag 'number', 1, min: 1, max: 190 %>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <%= submit_tag 'Cluster!' %>
            </div>
        </div>
    </div>
<% end -%>